apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbuddy-ingress
  namespace: chat-app
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "chatbuddy-backend"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: chat.172.83.83.241.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbuddy-frontend
            port:
              number: 80
