apiVersion: v1
kind: Secret
metadata:
  name: chatbuddy-secrets
  namespace: chat-app
type: Opaque
stringData:
  # Replace with your actual MongoDB Atlas or external MongoDB URL
  MONGODB_URI: "mongodb+srv://username:password@cluster.mongodb.net/chatbuddy?retryWrites=true&w=majority"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-use-32-chars-min"
  NODE_ENV: "production"
  # Optional: Add your Cloudinary credentials for image uploads
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
